name: CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build Rust WASM library
        run: wasm-pack build --release --target web ./json-sharpener-wasm

      - name: Move WASM to frontend
        working-directory: ./json-sharpener-web
        run: mkdir -p ./src/assets/wasm/ && cp ../json-sharpener-wasm/pkg/* ./src/assets/wasm/

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./json-sharpener-web
        run: npm install

      - name: Build frontend app
        working-directory: ./json-sharpener-web
        run: npm run build

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "./json-sharpener-web"
          output_location: "./json-sharpener-web/dist"
          action: "deploy"
